name: Crowdin Upload Action

on:
  push:
    paths:
      # Most translations
      - "*/locales"
    branches: [integration]

jobs:
  synchronize-core-frontend-translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crowdin sync
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: true
          download_translations: false
          source: /packages/webapp/public/locales/en/ # Sources pattern
          translation: /packages/webapp/public/locales/%two_letters_code%/%original_file_name% # Translations pattern
        env:
          GITHUB_TOKEN: ${{ secrets.CROWDIN_TEMP_PERSONAL_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
